#!/bin/bash


db2 connect to odsutils

ixf_dir=/cmdatalinux1/datatransfer/odsutils/tblspace/USERSPACE1
cd $ixf_dir
#db2 "load from tab13.ixf of  IXF  modified by identityoverride insert into APPDATA.CMSECTABLE1" >> "../odsutils.redo.import.txt"




db2 "load from tab14.ixf  of  IXF  modified by identityoverride insert into APPDATA.CMSECTABLE2" >> "../odsutils.redo.import.txt"         
db2 "load from tab15.ixf  of  IXF  modified by identityoverride insert into APPDATA.CMWBTABLEA" >> "../odsutils.redo.import.txt"
db2 "load from tab14.ixf  of  IXF  modified by identityoverride insert into APPDATA.CMWBTABLEW" >> "../odsutils.redo.import.txt"         
db2 "load from tab45.ixf  of  IXF  modified by identityoverride insert into APPDATA.ODS_CM_ATTRIBUTE" >> "../odsutils.redo.import.txt"   
db2 "load from tab50.ixf  of  IXF  modified by identityoverride insert into APPDATA.ODS_CM_FILE_TYPE_LOADER" >> "../odsutils.redo.import.txt"
db2 "load from tab51.ixf  of  IXF  modified by identityoverride insert into APPDATA.ODS_CM_ITEMTYPE" >> "../odsutils.redo.import.txt"    
db2 "load from tab53.ixf  of  IXF  modified by identityoverride insert into APPDATA.ODS_CM_ITEMTYPE_SECURITY_ACL" >> "../odsutils.redo.import.txt"
db2 "load from tab64.ixf  of  IXF  modified by identityoverride insert into APPDATA.ODS_CM_ITEMTYPE_SWAP" >> "../odsutils.redo.import.txt"
db2 "load from tab65.ixf  of  IXF  modified by identityoverride insert into APPDATA.ODS_CM_ITEMTYPE_WORKBASKET" >> "../odsutils.redo.import.txt"
db2 "load from tab71.ixf  of  IXF  modified by identityoverride insert into APPDATA.ODS_CM_REMOTE_DATABASES" >> "../odsutils.redo.import.txt"
db2 "load from tab72.ixf  of  IXF  modified by identityoverride insert into APPDATA.ODS_CM_REMOTE_DB_CONNECTION_INFO" >> "../odsutils.redo.import.txt"
db2 "load from tab73.ixf  of  IXF  modified by identityoverride insert into APPDATA.ODS_CM_REMOTE_DB_INDEX_QUERY" >> "../odsutils.redo.import.txt"
db2 "load from tab82.ixf  of  IXF  modified by identityoverride insert into APPDATA.UNIQUEITEMTYPE" >> "../odsutils.redo.import.txt"
