#!/bin/bash

db2stop force
ipclean
db2start 



db2 drop database ICMNLSDB
db2 drop database RMDB
db2 drop database ODSUTILS

rm -fr /db/*

#db2 connect to icmnlsdb
#db2 update db cfg using LOGARCHMETH1 DISK:/db/
#db2 connect to rmdb
#db2 update db cfg using LOGARCHMETH1 DISK:/db/
#db2 connect to odsutils
#db2 update db cfg using LOGARCHMETH1 DISK:/db/


db2stop force
ipclean
db2start 

echo ==============================================================
echo DB2 Database reset clean
echo ==============================================================

db2 create database ICMNLSDB
db2 create database RMDB
db2 create database ODSUTILS


#mkdir /db/bkp_emptydb
		
#dbs=('ICMNLSDB' 'RMDB' 'ODSUTILS')
		
		

#for d in "${dbs[@]}"
#do
#	db2 connect to $d
#	db2 quiesce database immediate force connections
#	db2 connect reset
#	db2 backup database $d to /db/bkp_emptydb compress without prompting
#echo $d
#done


